name: CI

on:
  push:
    branches: [ main, feature/hello-again-endpoint ]
  pull_request:
    branches: [ main, feature/hello-again-endpoint ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Run all tests
        run: ./mvnw test

      - name: Build application
        if: success()
        run: ./mvnw package
